[".antidote"]
    type = "git-repo"
    url = "https://github.com/mattmc3/antidote.git"
    refreshPeriod = "168h"
    [".antidote".clone]
        args = ["--depth", "1"]

[".zsh-patina"]
    type = "git-repo"
    url = "https://github.com/michel-kraemer/zsh-patina.git"
    refreshPeriod = "168h"
    [".zsh-patina".clone]
        args = ["--depth", "1"]
