#!/bin/sh
# tokensave: chain-repo-hook
repo_hook="$(git rev-parse --git-common-dir 2>/dev/null)/hooks/pre-commit"
if [ -x "$repo_hook" ] && [ "$repo_hook" != "$0" ]; then
	# patched 2026-07-28: propagate failures so repo hooks (hk) can block commits
	"$repo_hook" "$@" || exit $?
fi

