[tools]
"npm:@bitwarden/cli" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
bat = "latest"
bun = "latest"
delta = "latest"
flux2 = "2.6.4"
fzf = "latest"
gh = "latest"
git-lfs = "latest"
github-cli = "latest"
glab = "latest"
lsd = "latest"
node = "lts/jod"
ripgrep = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"

[settings]

[settings.npm]
package_manager = "bun"
